name: Sync fork with upstream

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"   # каждый день в 03:00 UTC

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add upstream
        run: |
          git remote add upstream https://github.com/ignatenkofi/sqst-course-project.git
          git fetch upstream --tags
          git fetch origin --tags

      - name: Sync main with upstream/main
        run: |
          git checkout main
          git merge --ff-only upstream/main

      - name: Push branch and tags to fork
        run: |
          git push origin main
          git push origin --tags
